"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {apiRequest,ApiError,API_BASE_URL} from "@/services/api";
import {authService} from "@/services/auth.service";

type User={fullName:string;phone:string;email:string};
type Profile={fullName:string;bloodGroup:string;contacts:{name:string;relationship:string;phone:string;primary:boolean}[];updatedAt:string};
type Qr={id:string;serialNumber:number;serialCode:string;status:string;publicUrl:string;createdAt:string};
type Order={id:string;orderNumber:string;product:string;paymentStatus:string;totalPaise:number;createdAt:string};
export default function Page(){
 const [user,setUser]=useState<User>();const [profile,setProfile]=useState<Profile>();const [qr,setQr]=useState<Qr[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [session,profileResult,qrResult,orderResult]=await Promise.all([authService.session(),apiRequest<Profile>("/emergency-profile").catch(e=>{if(e instanceof ApiError&&e.status===404)return undefined;throw e}),apiRequest<Qr[]>("/qr-codes"),apiRequest<Order[]>("/orders")]);setUser(session.user);setProfile(profileResult);setQr(qrResult);setOrders(orderResult)}catch(e){setError(e instanceof Error?e.message:"Could not load dashboard.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 if(loading)return <div className="text-slate-300">Loading your dashboard...</div>;
 if(error)return <div className="glass-panel p-6"><p role="alert" className="text-rescue">{error}</p><button onClick={()=>void load()} className="button button-primary mt-4">Retry</button></div>;
 return <div className="mx-auto max-w-6xl space-y-6"><header><span className="eyebrow">Customer hub</span><h1 className="display mt-2 text-3xl text-white">Welcome, {user?.fullName}</h1><p className="mt-2 text-sm text-slate-400">{user?.phone} · {user?.email}</p></header><div className="grid gap-4 sm:grid-cols-3">{[["My stickers",qr.length],["Emergency profiles",profile?1:0],["Orders",orders.length]].map(([label,count])=><div key={label} className="glass-panel p-5"><p className="text-xs text-slate-400">{label}</p><b className="mt-2 block text-3xl text-white">{count}</b></div>)}</div><div className="grid gap-5 lg:grid-cols-2"><section className="glass-panel p-6"><h2 className="text-xl font-bold text-white">Emergency profile</h2>{profile?<><p className="mt-3 text-slate-200">{profile.fullName} · {profile.bloodGroup}</p><p className="mt-2 text-xs text-emerald-400">Profile complete</p><p className="mt-2 text-sm text-slate-400">{profile.contacts.length} contact{profile.contacts.length===1?"":"s"} · Updated {new Date(profile.updatedAt).toLocaleDateString()}</p><Link className="button button-secondary mt-5" href="/dashboard/emergency-profile">Edit profile and contacts</Link></>:<><p className="mt-3 text-slate-400">No emergency profile saved yet.</p><Link className="button button-primary mt-5" href="/order">Create your QR</Link></>}</section><section className="glass-panel p-6"><h2 className="text-xl font-bold text-white">Stickers</h2>{qr.length?qr.map(item=><div key={item.id} className="mt-3 rounded-xl border border-white/10 p-4"><p className="font-bold text-white">Serial {item.serialCode} · {item.status}</p><p className="text-xs text-slate-400">Created {new Date(item.createdAt).toLocaleDateString()}</p>{item.status==="ACTIVE"&&<div className="mt-3 flex gap-4 text-sm text-safety"><a href={item.publicUrl} target="_blank" rel="noreferrer">Preview scan page</a><a href={`${API_BASE_URL}/qr-codes/${item.id}.png`} download>Download QR</a></div>}</div>):<p className="mt-3 text-slate-400">No purchased stickers yet.</p>}</section></div><section className="glass-panel p-6"><div className="flex justify-between"><h2 className="text-xl font-bold text-white">Recent orders</h2><Link href="/dashboard/orders" className="text-sm text-safety">View all</Link></div>{orders.length?orders.slice(0,3).map(order=><div className="mt-3 flex justify-between border-b border-white/10 py-3 text-sm" key={order.id}><span>{order.orderNumber} · {order.product}</span><span>{order.paymentStatus} · ₹{(order.totalPaise/100).toFixed(2)}</span></div>):<p className="mt-3 text-slate-400">No orders placed yet.</p>}</section></div>
}

